Server:
  RunMode: debug
  HttpPort: 80
  ReadTimeout: 60
  WriteTimeout: 60

App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log

Database:
  DBType: mysql
  Username: root
  Password: a12345678
  Host: 127.0.0.1:3306
  DBName: blog_service
  TablePrefix: blog_
  charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30